In [1]:
pip install statsbombpy

Requirement already satisfied: statsbombpy in /usr/local/lib/python3.12/dist-packages (1.18.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from statsbombpy) (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from statsbombpy) (2.32.4)
Requirement already satisfied: requests-cache in /usr/local/lib/python3.12/dist-packages (from statsbombpy) (1.3.2)
Requirement already satisfied: inflect in /usr/local/lib/python3.12/dist-packages (from statsbombpy) (7.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from statsbombpy) (1.5.3)
Requirement already satisfied: more_itertools>=8.5.0 in /usr/local/lib/python3.12/dist-packages (from inflect->statsbombpy) (10.8.0)
Requirement already satisfied: typeguard>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from inflect->statsbombpy) (4.5.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->statsbombpy) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->statsbombpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->statsbombpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->statsbombpy) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->statsbombpy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->statsbombpy) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->statsbombpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->statsbombpy) (2026.5.20)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache->statsbombpy) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache->statsbombpy) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache->statsbombpy) (4.9.6)
Requirement already satisfied: url-normalize>=2.0 in /usr/local/lib/python3.12/dist-packages (from requests-cache->statsbombpy) (3.0.0)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache->statsbombpy) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)

In [2]:
from statsbombpy import sb

In [3]:
import pandas as pd

url = "https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/3857256.json"

df = pd.read_json(url)

In [4]:
df.head()

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,interception,out,foul_won,dribble,block,foul_committed,ball_recovery,substitution,injury_stoppage,bad_behaviour
0,3727e9a2-082d-4e39-84e1-466b410822a3,1,1,2026-05-29 00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 786, 'name': 'Serbia'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4f087160-687b-4871-9fc2-ca1cc283878a,2,1,2026-05-29 00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 786, 'name': 'Serbia'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,03ecae65-85a3-44d0-9b1b-8d03df3e0f95,3,1,2026-05-29 00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 786, 'name': 'Serbia'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,829acb37-a66f-4179-a894-1c6a140bde31,4,1,2026-05-29 00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 786, 'name': 'Serbia'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,f5b59515-d259-43ef-b1c6-3854fdf2c135,5,1,2026-05-29 00:00:00.521,0,0,"{'id': 30, 'name': 'Pass'}",2,"{'id': 773, 'name': 'Switzerland'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type',
       'possession', 'possession_team', 'play_pattern', 'team', 'duration',
       'tactics', 'related_events', 'player', 'position', 'location', 'pass',
       'carry', 'ball_receipt', 'under_pressure', 'clearance', 'shot',
       'goalkeeper', 'off_camera', 'counterpress', 'duel', 'interception',
       'out', 'foul_won', 'dribble', 'block', 'foul_committed',
       'ball_recovery', 'substitution', 'injury_stoppage', 'bad_behaviour'],
      dtype='object')

In [6]:
corners = df[
    (df['type'].apply(lambda x: x['name']) == 'Pass') &
    (df['pass'].notna())
]

In [7]:
corners.head()

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,interception,out,foul_won,dribble,block,foul_committed,ball_recovery,substitution,injury_stoppage,bad_behaviour
4,f5b59515-d259-43ef-b1c6-3854fdf2c135,5,1,2026-05-29 00:00:00.521,0,0,"{'id': 30, 'name': 'Pass'}",2,"{'id': 773, 'name': 'Switzerland'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5dd326e4-edca-4458-b44b-277a3c7a1ea9,8,1,2026-05-29 00:00:03.385,0,3,"{'id': 30, 'name': 'Pass'}",2,"{'id': 773, 'name': 'Switzerland'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,4b8a468c-6a32-4fd8-aef1-1b5fefc673bc,11,1,2026-05-29 00:00:06.697,0,6,"{'id': 30, 'name': 'Pass'}",2,"{'id': 773, 'name': 'Switzerland'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,3d9b3da9-f6d4-45e9-af5a-6cf7df640981,13,1,2026-05-29 00:00:08.484,0,8,"{'id': 30, 'name': 'Pass'}",2,"{'id': 773, 'name': 'Switzerland'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,10ce0f7f-3785-48eb-92ed-779f1ca09945,16,1,2026-05-29 00:00:15.905,0,15,"{'id': 30, 'name': 'Pass'}",2,"{'id': 773, 'name': 'Switzerland'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
import json
import requests
import pandas as pd

url = "https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/3764440.json"

data = requests.get(url).json()

df = pd.json_normalize(data)

In [9]:
df.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'possession',
       'duration', 'type.id', 'type.name',
       ...
       'substitution.outcome.name', 'substitution.replacement.id',
       'substitution.replacement.name', 'pass.goal_assist', '50_50.outcome.id',
       '50_50.outcome.name', 'shot.first_time', 'shot.aerial_won',
       'injury_stoppage.in_chain', 'shot.one_on_one'],
      dtype='object', length=112)

In [10]:
corners = df[
    (df['type.name'] == 'Pass') &
    (df['pass.type.name'] == 'Corner')
]

In [11]:
corners.head()

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,substitution.outcome.name,substitution.replacement.id,substitution.replacement.name,pass.goal_assist,50_50.outcome.id,50_50.outcome.name,shot.first_time,shot.aerial_won,injury_stoppage.in_chain,shot.one_on_one
562,6a0632ec-9ed1-4035-98a4-c50b892e516d,563,1,00:12:41.557,12,41,21,1.265497,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889,02e3cfca-4f50-4a92-8f1f-b8ffafda4225,890,1,00:18:38.038,18,38,29,1.200106,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1114,0a91219c-68ed-46c6-8a72-a2988f7a1c05,1115,1,00:22:43.567,22,43,37,1.173397,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1123,cdd4a4a8-a66c-44c8-a6a7-23f68213e2be,1124,1,00:23:05.521,23,5,38,1.133589,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1472,f148bd58-ca2c-4606-801e-e4c44ee4b6e4,1473,1,00:32:43.413,32,43,52,4.047052,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
corners[
    ['minute',
     'second',
     'team.name',
     'player.name',
     'location',
     'pass.end_location']
].head()

,minute,second,team.name,player.name,location,pass.end_location
562,12,41,Elche,Emiliano Ariel Rigoni,"[120.0, 0.1]","[110.0, 33.1]"
889,18,38,Elche,Emiliano Ariel Rigoni,"[120.0, 80.0]","[114.3, 47.3]"
1114,22,43,Barcelona,Pedro González López,"[120.0, 0.1]","[109.1, 3.7]"
1123,23,5,Barcelona,Lionel Andrés Messi Cuccittini,"[120.0, 0.1]","[113.3, 38.2]"
1472,32,43,Elche,Emiliano Ariel Rigoni,"[120.0, 80.0]","[99.4, 18.1]"

In [13]:
corner_index = corners.index[0]

In [14]:
df.iloc[corner_index:corner_index+8][
    ['type.name',
     'team.name',
     'player.name']
]

,type.name,team.name,player.name
562,Pass,Elche,Emiliano Ariel Rigoni
563,Pressure,Barcelona,Gerard Piqué Bernabéu
564,Ball Receipt*,Elche,Pere Milla Peña
565,Miscontrol,Elche,Pere Milla Peña
566,Pass,Elche,Emiliano Ariel Rigoni
567,Block,Barcelona,Miralem Pjanić
568,Ball Recovery,Barcelona,Francisco António Machado Mota de Castro Trincão
569,Carry,Barcelona,Francisco António Machado Mota de Castro Trincão

# 1. First Contact Control Index

# STEP 1 — Extract Corners

In [15]:
corners = df[
    (df['type.name'] == 'Pass') &
    (df['pass.type.name'] == 'Corner')
]

# Find First Event After Each Corner

In [16]:
for idx in corners.index:

    next_events = df.iloc[idx+1:idx+6]

    print(next_events[['type.name', 'team.name']])

         type.name  team.name
563       Pressure  Barcelona
564  Ball Receipt*      Elche
565     Miscontrol      Elche
566           Pass      Elche
567          Block  Barcelona
         type.name  team.name
890      Clearance  Barcelona
891  Ball Recovery  Barcelona
892          Carry  Barcelona
893       Pressure      Elche
894           Pass  Barcelona
          type.name  team.name
1115  Ball Receipt*  Barcelona
1116          Carry  Barcelona
1117           Pass  Barcelona
1118  Ball Receipt*  Barcelona
1119          Carry  Barcelona
          type.name  team.name
1124           Duel  Barcelona
1125      Clearance      Elche
1126           Pass  Barcelona
1127  Ball Receipt*  Barcelona
1128          Carry  Barcelona
          type.name  team.name
1473       Pressure  Barcelona
1474  Ball Receipt*      Elche
1475          Carry      Elche
1476           Pass      Elche
1477  Ball Receipt*      Elche
          type.name  team.name
1984  Ball Receipt*  Barcelona
1985          Carry  Barcelona
1986       Pressure      Elche
1987           Pass  Barcelona
1988  Ball Receipt*  Barcelona
          type.name  team.name
2547  Ball Receipt*  Barcelona
2548          Carry  Barcelona
2549           Pass  Barcelona
2550  Ball Receipt*  Barcelona
2551           Pass  Barcelona
          type.name  team.name
2574  Ball Receipt*  Barcelona
2575          Carry  Barcelona
2576           Pass  Barcelona
2577  Ball Receipt*  Barcelona
2578          Carry  Barcelona
          type.name  team.name
3862  Ball Receipt*  Barcelona
3863          Carry  Barcelona
3864           Pass  Barcelona
3865  Ball Receipt*  Barcelona
3866          Carry  Barcelona

# Define First Contact Logic

In [17]:
key_events = [
    'Clearance',
    'Duel',
    'Shot',
    'Block',
    'Interception',
    'Ball Recovery'
]

def get_first_contact(df, idx):
    for i in range(idx+1, idx+15):
        event = df.iloc[i]

        if event['type.name'] in key_events:
            return event['type.name'], event['team.name']

    return None, None

In [18]:
results = []

In [19]:
for idx in corners.index:

    event_type, team = get_first_contact(df, idx)

    results.append({
        "corner_index": idx,
        "defending_team": team,
        "first_contact_event": event_type
    })

# Build Dataset

In [20]:
fc_df = pd.DataFrame(results)

In [21]:
fc_df = fc_df.dropna()

In [22]:
def label_outcome(event):
    if event in ["Clearance", "Interception", "Duel"]:
        return "Defensive Win"
    elif event == "Shot":
        return "Dangerous"
    elif event == "Ball Recovery":
        return "Second Phase Loss"
    else:
        return "Other"

In [23]:
fc_df["outcome"] = fc_df["first_contact_event"].apply(label_outcome)

In [24]:
summary = fc_df.groupby("defending_team")["outcome"].value_counts().unstack()

In [25]:
summary["total"] = summary.sum(axis=1)
summary["defensive_win_pct"] = summary["Defensive Win"] / summary["total"] * 100
summary["danger_pct"] = summary["Dangerous"] / summary["total"] * 100

In [26]:
summary["control_index"] = summary["defensive_win_pct"] - summary["danger_pct"]

In [27]:
idx = corners.index[0]

event_type, team = get_first_contact(df, idx)

print(event_type, team)

Block Barcelona

In [28]:
def get_first_contact_score(df, idx):

    for i in range(idx+1, idx+20):

        event = df.iloc[i]

        etype = event['type.name']

        if etype == 'Clearance':
            return "Clearance", 1

        elif etype == 'Interception':
            return "Interception", 1

        elif etype == 'Block':
            return "Block", 0.8

        elif etype == 'Duel':
            return "Duel", 1

        elif etype == 'Shot':
            return "Shot", -1

        elif etype == 'Goal':
            return "Goal", -2

    return "None", 0

In [29]:
results = []

for idx in corners.index:

    event, score = get_first_contact_score(df, idx)

    results.append({
        "corner_index": idx,
        "defending_team": corners.loc[idx, "team.name"],
        "event": event,
        "score": score
    })

fc_df = pd.DataFrame(results)

In [30]:
team_index = fc_df.groupby("defending_team")["score"].sum()
team_total = fc_df.groupby("defending_team")["score"].count()

fcci = (team_index / team_total) * 100

In [31]:
def get_first_contact(df, idx):

    for i in range(idx+1, idx+20):

        event = df.iloc[i]
        etype = event['type.name']

        if etype in [
            "Clearance",
            "Shot",
            "Duel",
            "Interception",
            "Block"
        ]:
            return etype, event['team.name']

    return None, None

In [32]:
idx = corners.index[0]

event, team = get_first_contact(df, idx)

print(event, team)

Block Barcelona

In [33]:
results = []

In [34]:
for idx in corners.index:

    event, team = get_first_contact(df, idx)

    defending_team = corners.loc[idx, "team.name"]

    # classify outcome
    if event in ["Clearance", "Interception", "Block", "Duel"]:
        outcome = "Control"

    elif event == "Shot":
        outcome = "Danger"

    else:
        outcome = "Neutral"

    results.append({
        "corner_index": idx,
        "defending_team": defending_team,
        "event": event,
        "controlling_team": team,
        "outcome": outcome
    })

In [35]:
fc_df = pd.DataFrame(results)

In [36]:
fc_df.head()

   corner_index defending_team      event controlling_team  outcome
0           562          Elche      Block        Barcelona  Control
1           889          Elche  Clearance        Barcelona  Control
2          1114      Barcelona      Block            Elche  Control
3          1123      Barcelona       Duel        Barcelona  Control
4          1472          Elche       Shot            Elche   Danger

In [37]:
fc_df["outcome"].value_counts()

outcome
Control    6
Neutral    2
Danger     1
Name: count, dtype: int64

In [38]:
fc_df.groupby("defending_team")["outcome"].value_counts()

defending_team  outcome
Barcelona       Control    4
                Neutral    2
Elche           Control    2
                Danger     1
Name: count, dtype: int64

# Who controls the first contact after the corner is delivered?
First Contact Control Index

# STEP 1 — Find corners

In [39]:
corners = df[df['type.name'] == 'Pass']
corners = corners[corners['pass.type.name'] == 'Corner']

In [40]:
priority = {
    "Shot": 3,
    "Clearance": 2,
    "Block": 2,
    "Interception": 2,
    "Duel": 1,
    "Ball Receipt*": 1,
    "Miscontrol": 1
}

In [41]:
def get_first_contact(df, idx):

    best_event = None
    best_score = 0

    for i in range(idx+1, idx+10):

        event = df.iloc[i]
        etype = event['type.name']

        if etype in priority:

            if priority[etype] > best_score:
                best_event = (etype, event['team.name'])
                best_score = priority[etype]

    return best_event if best_event else (None, None)

In [42]:
results = []

for idx in corners.index:

    event, team = get_first_contact(df, idx)

    results.append({
        "corner_index": idx,
        "event": event,
        "team": team
    })

fc_df = pd.DataFrame(results)

In [43]:
def classify(event):

    if event in ["Clearance", "Block", "Interception"]:
        return "Win"

    elif event in ["Duel", "Ball Receipt*", "Miscontrol"]:
        return "Contested"

    elif event == "Shot":
        return "Danger"

    else:
        return "Other"

In [44]:
fc_df["outcome"] = fc_df["event"].apply(classify)

In [45]:
win_rate = (fc_df["outcome"] == "Win").mean() * 100

In [46]:
print(win_rate)

44.44444444444444

In [47]:
danger_rate = (fc_df["outcome"] == "Danger").mean() * 100

In [48]:
print(danger_rate)

11.11111111111111

In [49]:
fc_df.head()

   corner_index      event       team outcome
0           562      Block  Barcelona     Win
1           889  Clearance  Barcelona     Win
2          1114      Block      Elche     Win
3          1123  Clearance      Elche     Win
4          1472       Shot      Elche  Danger

In [50]:
fc_df["outcome"].value_counts()

outcome
Win          4
Contested    4
Danger       1
Name: count, dtype: int64

1. Win = 44%
Defenders are winning almost half of first contacts
This is strong but not dominant
Typical of balanced matchups
🟡 2. Contested = 44%
Most corners are still decided by aerial/physical battles
This is completely realistic in football
This is where set-pieces are actually decided
🔴 3. Danger = 11%
Low but meaningful
Shows occasional breakdowns in structure

# Load Multiple Match Event Files

In [51]:
import pandas as pd
import requests

In [52]:
def load_events(match_id):

    url = f"https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/{match_id}.json"

    data = requests.get(url).json()

    return pd.json_normalize(data)

In [53]:
priority = {
    "Shot": 3,
    "Clearance": 2,
    "Block": 2,
    "Interception": 2,
    "Duel": 1,
    "Ball Receipt*": 1,
    "Miscontrol": 1
}

def get_first_contact(df, idx):

    best_event = None
    best_score = 0

    max_index = min(idx + 10, len(df))

    for i in range(idx + 1, max_index):

        event = df.iloc[i]
        etype = event.get("type.name", None)
        team = event.get("team.name", None)

        if etype in priority and team is not None:

            if priority[etype] > best_score:
                best_event = (etype, team)
                best_score = priority[etype]

    return best_event if best_event else (None, None)

In [54]:
def classify(event):

    if event in ["Clearance", "Block", "Interception"]:
        return "Win"

    elif event == "Shot":
        return "Danger"

    elif event in ["Duel", "Ball Receipt*", "Miscontrol"]:
        return "Contested"

    return "Other"

In [55]:
match_ids = [3764440, 3764661, 3773369, 3773372, 3773377]

results = []

for match_id in match_ids:

    df = load_events(match_id)

    corners = df[
        (df["type.name"] == "Pass") &
        (df["pass.type.name"] == "Corner")
    ]

    for idx in corners.index:

        event, team = get_first_contact(df, idx)

        if event is None or team is None:
            continue

        results.append({
            "match_id": match_id,
            "team": team,
            "event": event,
            "outcome": classify(event)
        })

fc_df = pd.DataFrame(results)

In [56]:
print(fc_df.head())
print(fc_df.columns)
print(fc_df["team"].value_counts())

   match_id       team      event outcome
0   3764440  Barcelona      Block     Win
1   3764440  Barcelona  Clearance     Win
2   3764440      Elche      Block     Win
3   3764440      Elche  Clearance     Win
4   3764440      Elche       Shot  Danger
Index(['match_id', 'team', 'event', 'outcome'], dtype='object')
team
Barcelona          28
Valencia            7
Atlético Madrid     4
Huesca              4
Elche               3
Athletic Club       3
Name: count, dtype: int64

In [57]:
comparison = fc_df.groupby("team").agg(
    Total_Corners=("outcome", "count"),
    Wins=("outcome", lambda x: (x == "Win").sum()),
    Danger=("outcome", lambda x: (x == "Danger").sum())
).reset_index()

comparison["Win Rate"] = (comparison["Wins"] / comparison["Total_Corners"]) * 100
comparison["Danger Rate"] = (comparison["Danger"] / comparison["Total_Corners"]) * 100
comparison["FCCI"] = comparison["Win Rate"] - comparison["Danger Rate"]

In [58]:
comparison.head()

,team,Total_Corners,Wins,Danger,Win Rate,Danger Rate,FCCI
0,Athletic Club,3,2,0,66.666667,0.000000,66.666667
1,Atlético Madrid,4,1,2,25.000000,50.000000,-25.000000
2,Barcelona,28,8,6,28.571429,21.428571,7.142857
3,Elche,3,2,1,66.666667,33.333333,33.333333
4,Huesca,4,3,1,75.000000,25.000000,50.000000

In [59]:
matches_url = "https://raw.githubusercontent.com/statsbomb/open-data/master/data/matches/11/90.json"
matches = pd.read_json(matches_url)

match_ids = matches["match_id"].tolist()

In [60]:
results = []

for match_id in match_ids:

    df = load_events(match_id)

    corners = df[
        (df["type.name"] == "Pass") &
        (df["pass.type.name"] == "Corner")
    ]

    for idx in corners.index:

        event, team = get_first_contact(df, idx)

        if event is None or team is None:
            continue

        results.append({
            "match_id": match_id,
            "team": team,
            "event": event,
            "outcome": classify(event)
        })

In [61]:
league_df = pd.DataFrame(results)

league_table = league_df.groupby("team").agg(
    Total_Corners=("outcome", "count"),
    Wins=("outcome", lambda x: (x == "Win").sum()),
    Danger=("outcome", lambda x: (x == "Danger").sum())
).reset_index()

league_table["Win Rate"] = league_table["Wins"] / league_table["Total_Corners"] * 100
league_table["Danger Rate"] = league_table["Danger"] / league_table["Total_Corners"] * 100
league_table["FCCI"] = league_table["Win Rate"] - league_table["Danger Rate"]

In [63]:
league_table.head(20)

,team,Total_Corners,Wins,Danger,Win Rate,Danger Rate,FCCI
0,Athletic Club,7,5,0,71.428571,0.000000,71.428571
1,Atlético Madrid,13,7,4,53.846154,30.769231,23.076923
2,Barcelona,178,50,34,28.089888,19.101124,8.988764
3,Celta Vigo,11,5,1,45.454545,9.090909,36.363636
4,Cádiz,12,7,1,58.333333,8.333333,50.000000
5,Deportivo Alavés,4,4,0,100.000000,0.000000,100.000000
6,Elche,3,2,1,66.666667,33.333333,33.333333
7,Getafe,5,1,1,20.000000,20.000000,0.000000
8,Granada,4,1,1,25.000000,25.000000,0.000000
9,Huesca,6,4,2,66.666667,33.333333,33.333333
10,Levante UD,12,4,5,33.333333,41.666667,-8.333333
11,Osasuna,8,5,1,62.500000,12.500000,50.000000
12,Real Betis,8,3,4,37.500000,50.000000,-12.500000
13,Real Madrid,16,9,4,56.250000,25.000000,31.250000
14,Real Sociedad,3,1,1,33.333333,33.333333,0.000000
15,Real Valladolid,6,3,0,50.000000,0.000000,50.000000
16,Sevilla,11,3,5,27.272727,45.454545,-18.181818
17,Valencia,8,4,3,50.000000,37.500000,12.500000
18,Villarreal,14,2,4,14.285714,28.571429,-14.285714